### ISSUE TITLE
Dll load failed

### ISSUE THREAD

**Issue by hsqaihkl** [lxlscut/Direct_Photometric_Alignment_by_Mesh_Deformation#1]
@lxlscut 
Hi,lxlcut.My name is Water,I am try to run your code in windos10 python3.7,but I met a problem:

File "d:/Download/Github/Direct_Photometric_Alignment_by_Mesh_Deformation/main_g.py", line 14, in <module>
    import optimization
ImportError: DLL load failed: 找不到指定的模块。
 Could you help me？

**Comment by lxlscut** [comment]
i think you could try python 3.6, it's the version i used for compiling the pyd file.

**Comment by hsqaihkl** [comment]
Are you chiness? Could I have your wechat?     My wechat :18025361214

**Comment by hsqaihkl** [comment]
@lxlscut  
Hi ，I am try you suggestion and recomplie the pyd file ,it work!
Thanks.

**Comment by lxlscut** [comment]
不用谢，跑通了就好。
